PERIOD_DAY = "day"
PERIOD_WEEK = "week"
PERIOD_MONTH = "month"
PERIOD_TYPES = frozenset({PERIOD_DAY, PERIOD_WEEK, PERIOD_MONTH})

CHART_BUCKET_LIMIT = 10

NO_TRACKED_DATA = "NO_TRACKED_DATA"
NO_PERIOD_DATA = "NO_PERIOD_DATA"
NO_DAY_DETAIL_DATA = "NO_DAY_DETAIL_DATA"

DASHBOARD_RATE_LIMIT_NAME = "analytics_dashboard_read"
DAILY_LOG_DETAIL_RATE_LIMIT_NAME = "daily_log_detail_read"
